export const transactions = [
  {
    id: 1,
    name: "Grocery Shopping",
    date: "2025-06-25",
    category: "Groceries",
    icon: "ShoppingCart",
    iconColor: "#EF4444",
    amount: -1500.75,
    account: "Cash",
    notes: "Bought weekly groceries at the supermarket",
    type: "Expenses",
  },
  {
    id: 2,
    name: "Salary",
    date: "2025-06-23",
    category: "Income",
    icon: "DollarSign",
    iconColor: "#10B981",
    amount: 50000.0,
    account: "Cash",
    notes: "Monthly salary credited",
    type: "Income",
  },
  {
    id: 3,
    name: "Electric Bill",
    date: "2025-06-18",
    category: "Utilities",
    icon: "Zap",
    iconColor: "#F59E0B",
    amount: -3500.0,
    account: "Cash",
    notes: "Paid June electric bill",
    type: "Expenses",
  },
  {
    id: 4,
    name: "Dining Out",
    date: "2025-06-07",
    category: "Food & Drinks",
    icon: "Coffee",
    iconColor: "#EF4444",
    amount: -1200.0,
    account: "Cash",
    notes: "Dinner at a restaurant",
    type: "Expenses",
  },
  {
    id: 5,
    name: "Freelance Payment",
    date: "2025-06-05",
    category: "Income",
    icon: "Briefcase",
    iconColor: "#10B981",
    amount: 15000.0,
    account: "Cash",
    notes: "Payment for freelance project",
    type: "Income",
  },
  {
    id: 6,
    name: "Freelance Payment",
    date: "2025-06-05",
    category: "Income",
    icon: "Briefcase",
    iconColor: "#10B981",
    amount: 15000.0,
    account: "Cash",
    notes: "Payment for another freelance project",
    type: "Income",
  },
  {
    id: 7,
    name: "Online Shopping",
    date: "2025-06-04",
    category: "Shopping",
    icon: "ShoppingCart",
    iconColor: "#0077B6",
    amount: -2500.0,
    account: "BPI",
    notes: "New clothes from online store",
    type: "Expenses",
  },
  {
    id: 8,
    name: "Taxi Fare",
    date: "2025-06-11",
    category: "Transportation",
    icon: "BusFront",
    iconColor: "#FCBF49",
    amount: -350.0,
    account: "Wallet",
    notes: "Taxi to the office",
    type: "Expenses",
  },
  {
    id: 9,
    name: "Doctor's Consultation",
    date: "2025-05-20",
    category: "Health",
    icon: "HeartPulse",
    iconColor: "#E63946",
    amount: -1000.0,
    account: "Savings",
    notes: "Regular check-up",
    type: "Expenses",
  },
  {
    id: 10,
    name: "Streaming Subscription",
    date: "2025-06-10",
    category: "Entertainment",
    icon: "Clapperboard",
    iconColor: "#457B9D",
    amount: -599.0,
    account: "BPI",
    notes: "Monthly subscription fee",
    type: "Expenses",
  },
  {
    id: 11,
    name: "Rent Payment",
    date: "2025-05-30",
    category: "Housing",
    icon: "House",
    iconColor: "#003049",
    amount: -12000.0,
    account: "Savings",
    notes: "Rent for June",
    type: "Expenses",
  },
  {
    id: 12,
    name: "Internet Bill",
    date: "2025-06-01",
    category: "Utilities",
    icon: "Lightbulb",
    iconColor: "#F77F00",
    amount: -1299.0,
    account: "BPI",
    notes: "Monthly internet bill",
    type: "Expenses",
  },
  {
    id: 13,
    name: "Stock Dividends",
    date: "2025-05-15",
    category: "Income",
    icon: "DollarSign",
    iconColor: "#10B981",
    amount: 7500.0,
    account: "Savings",
    notes: "Dividends from stock investments",
    type: "Income",
  },
  {
    id: 14,
    name: "Gasoline",
    date: "2025-06-06",
    category: "Transportation",
    icon: "BusFront",
    iconColor: "#FCBF49",
    amount: -2000.0,
    account: "Cash",
    notes: "Full tank for the car",
    type: "Expenses",
  },
  {
    id: 15,
    name: "Movie Tickets",
    date: "2025-06-13",
    category: "Entertainment",
    icon: "Clapperboard",
    iconColor: "#457B9D",
    amount: -700.0,
    account: "Wallet",
    notes: "Watched a new movie with a friend",
    type: "Expenses",
  },
  {
    id: 16,
    name: "Gym Membership",
    date: "2025-06-01",
    category: "Health",
    icon: "HeartPulse",
    iconColor: "#E63946",
    amount: -2500.0,
    account: "BPI",
    notes: "Monthly gym fee",
    type: "Expenses",
  },
  {
    id: 17,
    name: "Birthday Gift",
    date: "2025-05-25",
    category: "Shopping",
    icon: "ShoppingCart",
    iconColor: "#0077B6",
    amount: -1500.0,
    account: "Cash",
    notes: "Gift for a friend's birthday",
    type: "Expenses",
  },
  {
    id: 18,
    name: "Consulting Gig",
    date: "2025-06-14",
    category: "Income",
    icon: "Briefcase",
    iconColor: "#10B981",
    amount: 25000.0,
    account: "BPI",
    notes: "Payment for a short consulting project",
    type: "Income",
  },
  {
    id: 19,
    name: "Book Purchase",
    date: "2025-06-03",
    category: "Shopping",
    icon: "ShoppingCart",
    iconColor: "#0077B6",
    amount: -800.0,
    account: "Wallet",
    notes: "Bought a new novel",
    type: "Expenses",
  },
  {
    id: 20,
    name: "Lunch with Friends",
    date: "2024-06-12",
    category: "Food & Drinks",
    icon: "Coffee",
    iconColor: "#EF4444",
    amount: -950.0,
    account: "Cash",
    notes: "Lunch at a cafe",
    type: "Expenses",
  },
];
